---
name: xcop
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  xcop:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: g4s8/xcop-action@master
